name: kindershala
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  shared_preferences: 2.0.0
  camera:
  google_ml_kit: ^0.9.0
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  google_nav_bar: ^5.0.6
  #firebase_ml_vision: ^0.12.0+3
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/images/onboarding/
  - assets/images/auth/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900

 
